name: Pull Request Container Scan

on:
  pull_request:
    branches: 
      - master
env:
  CONTAINER_REGISTRY: dsmsacr.azurecr.io   # set secret with Container Registry name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
        
    - name: Docker build
      run: |
       docker build -f ${{ github.workspace }}/Dockerfile -t ${{ env.CONTAINER_REGISTRY }}/nodejsapp:${{ github.sha }}

    - name: Container scan
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ env.CONTAINER_REGISTRY }}/nodejsapp:${{ github.sha }}
